### ISSUE TITLE
SSH access to WWW server

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#18]
With the move to the new page, the discusses SSH access should be granted.

**Comment by johnbent** [comment]
'discusses SSH access' ?  I'm not sure I understand this one.

Are you asking about the disqus login?  We are just use the committee@io500.org account for that so access is already shared by the committe.

**Comment by JulianKunkel** [comment]
I recall that you promised that on the new server we have SSH access
as it was so important for you. That is the reminder about it.

**Comment by johnbent** [comment]
Oh, I am happy that you also consider this important.  OK, you can now 'ssh io500@io500.org' and use the same password that we use for our committee@io500.org mailbox.  Let me know if you also want a personal ssh account as well as a subdomain so that you can easily co the web pages and edit them and look live at your changes.
________________________________

**Comment by adilger** [comment]
Rather than using passwords for SSH access, it is much more secure to use SSH keys added to the .ssh/authorized_keys file and disallow password access entirely. 

That avoids all chance of hacking the password, and allows adding/removing keys as needed without having to change a shared password. 

Cheers, Andreas

**Comment by johnbent** [comment]
Is there a way to have a shared ssh key for committee?  Or should we all just have individual accounts?

John Bent (he/him/his)
Seagate Managing Technologist
505.795.3167
john.bent@seagate.com
________________________________

**Comment by adilger** [comment]
It is much better to use individual keys. That allows each user to just use their own key (hopefully with a strong password), probably the same key as for GitHub. If there is a reason to remove access for a user, then just their key would be removed from the host. 

Cheers, Andreas

**Comment by johnbent** [comment]
Cool.  We'll set this up on the new server when it's  ready.

**Comment by jeanbez** [comment]
@adilger Since this is not directly related to the website, but more of a configuration, and I believe this has been addressed, can we close this issue as well?
