### ISSUE TITLE
Internal server error when sorting by rank

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#2]
On the page: https://www.jbez.io500.org/site/releases/full, clicking on "#" which is rank, leads to server error https://www.jbez.io500.org/site/releases/full?sort=rank&direction=asc

**Comment by jeanbez** [comment]
@JulianKunkel I opened a merge request with the fix

**Comment by johnbent** [comment]
You're the best Jean Luca!

**Comment by adilger** [comment]
I verified that the sorting of various fields does not cause any error.

Selecting the _same_ column changed the sort direction as expected.   However, there was a bit of strangeness when selecting different columns.   Not only did the sort column change, it *also* changed the sort direction, so clicking "`BW`" would cause it to sort by smallest bandwidth first, and a second click was needed to sort from highest bandwidth first.  Then, clicking on "`MD`" caused it to sort by smallest MD IOPS first, instead of just changing the sort column to keep the same order.

Actually, it seems that the default sort order is *always* "smallest first" instead of "largest first" as I would expect from any of the scores.  Maybe it would be better to remove the "`#`" header entirely, and just display ranks based on the "`Score`" column and change the default sort order to descending, or do we want to keep an assigned rank separately from the score? @JulianKunkel @johnbent 

Or should we have a different default sorting order per column (e.g. ascending for rank, names - all strings; descending for score, MD, BW, clients, procs, nodes, etc? - all numbers)?

**Comment by johnbent** [comment]
I don't think we need a separate rank field.  Although it might be useful for people when commenting / discussing the submissions.  If we only had score, then default descending by all columns would be sensible for sure.  If we add rank, then just it should default to ascend I would think.  However, we do potentially have other fields we can start adding later.  Like we can parse the IOR and start putting 'ior_runtime_seconds' in there and then it should sort them by ascend.  That's useful to see straggler effect for example.

**Comment by johnbent** [comment]
I think the default sorting order for rank should be ascend.
I think the default sorting order for rate fields should be descend.
I think the default sorting order for time fields should be ascend.
I think the default sorting order for text fields should be alpha (case insensitive).
I think that should cover every column in the DB.

Jean-Luca, can we do this please?
