### ISSUE TITLE
Submitted items in full list that shouldn't be there.

### ISSUE THREAD

**Issue by JulianKunkel** [IO500/webpage#67]
I had marked upon submission the two submissions to be *not* included in the full list, but they appear:
https://io500.org/site/submissions/view/472
https://io500.org/site/submissions/view/474
Please remove them.

The 10 node submission can remain in 10node.

**Comment by adilger** [comment]
The 474 submission should be excluded from the overall ranked list "algorithmically" rather than setting the "do not show in ranked list" flag, because we should not rank any system with fewer than 10 client nodes.

I tried looking in `templates/Submissions/ten.php` and `.../list.php` to see if there was logic in those files that determined which submissions were included in each list, and possibly submit a patch for this, but I couldn't find anything to that effect.

**Comment by adilger** [comment]
this logic is in src/Controller/SubmissionsController.php and was fixed via PR #82
